### ISSUE TITLE
Voices

### ISSUE THREAD

**Issue by plagasul** [connornishijima/80speak#1]
This is more a question than an issue.

First, congrats for the work!

Is only perfect paul available in the dectalk package you included ? or are all of the original dectalk voices there aswell?

thanks

**Comment by connornishijima** [comment]
In the _dectalk_ directory, there are two executables: **say.exe** and **speak.exe**.

**say.exe** is CLI-only, which is good for scripting. You can use an argument list like this to set up a new voice:

say.exe -pre "[:nb]" "hello, plagasul!"

**-pre** allows for sending commands to DECTalk before speech synthesis, [here are some of those commands](http://www.novaresearch.com/QDS/QDSHelp/the_audio_computer_administered_self_interview__acasi__module/using_audio/dectalk_text_to_speech/dectalk_commands.htm).

**[:nb]** is the command to switch to Betty's voice in this instance, and our phrase to speak is the final argument in quotations.

Or, to just play with the voices, **speak.exe** is a GUI interface for them. Windows Defender might get nervous about running it either due to age or vendor, but it's never hurt me. :)

**Comment by plagasul** [comment]
Great! yes, a CLI dectalk is great to have, thank you. Do you have any idea if it can also sing using the syntax described here? https://msu.edu/course/asc/232/song_project/dectalk_pages/DECtalk%20Singing.html

`[phoneme<duration, pitch number>]`

**Comment by connornishijima** [comment]
It should, I believe those bracketed phoneme commands can be placed _within_ a phrase for [awesome Grease covers](https://www.youtube.com/watch?v=L4Xy_VAEYBc&index=1&list=PLYQzAy4_dsEiYO6OznVAMknJnN3s2cOrH).

**Comment by plagasul** [comment]
:+1: I'll give it a try, I've been wanting to program a CLI dectalk based choir. I enjoy the flexibility of early TTS engines.

Thanks again

**Comment by connornishijima** [comment]
No problem! If you get a DECTalk choir running in some multithreaded config feel free to open another issue here just to share it - I'd love to see!
